services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - TZ=YOUR_TIMEZONE
    devices:
      - /dev/ttyACM0:/dev/zwave
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - 8091:8091
      - 3001:3000
    group_add:
      - dialout
